import {aiJSON} from "../../../lib/ai.js";
import {validateLeadAnalysis} from "../../../lib/ai-schema.js";
import {bearerToken,getAuthenticatedUser,supabaseRequest} from "../../../lib/supabase.js";
import {isInternalRequest} from "../../../lib/internal-auth.js";
import {assertLeadOwner} from "../../../lib/authz.js";
import {body} from "../../../lib/validation.js";
export const methods=["POST"];
export default async function(req,res){try{
 const id=req.query?.id||new URL(req.url,"http://localhost").pathname.split("/").filter(Boolean).slice(-2,-1)[0];if(!id)return res.status(400).json({error:"lead id is required"});
 const token=bearerToken(req),internal=isInternalRequest(req),lead=(await supabaseRequest("leads?id=eq."+encodeURIComponent(id)+"&select=*",{accessToken:internal?undefined:token}))[0];if(!lead)return res.status(404).json({error:"Lead not found"});
 if(!internal){const user=await getAuthenticatedUser(token);await assertLeadOwner(id,user.id,token);}
 const input=body(req);const previous=lead.raw_data?.last_analysis;if(previous&&!input.force){const existing=await supabaseRequest("lead_opportunities?lead_id=eq."+encodeURIComponent(id)+"&select=*&order=created_at.desc",{accessToken:internal?undefined:token});return res.json({lead_id:id,analysis:previous,opportunities:existing,idempotent:true});}
 const result=validateLeadAnalysis(await aiJSON([{role:"system",content:"You are the Lead Hunter and service opportunity analyst. Analyze only supplied lead data. Return JSON with opportunities for website, app, automation, ai_video and uiux. Include service, score, confidence, reason, evidence, recommended_solution, estimated_value, plus service-specific fields."},{role:"user",content:JSON.stringify({lead})}],{maxTokens:6500}));
 const opportunities=result.opportunities,created=[];
 for(const o of opportunities){
  const existing=(await supabaseRequest("lead_opportunities?lead_id=eq."+encodeURIComponent(id)+"&service=eq."+encodeURIComponent(o.service)+"&order=created_at.desc&limit=1&select=*",{accessToken:internal?undefined:token}))[0];
  const payload={lead_id:id,service:o.service,score:Number(o.score||0),confidence:Number(o.confidence||0),reason:o.reason||null,evidence:o.evidence||[],recommended_solution:o.recommended_solution||null,estimated_value:o.estimated_value==null?null:Number(o.estimated_value),status:existing?.status||"identified"};
  const row=existing?(await supabaseRequest("lead_opportunities?id=eq."+encodeURIComponent(existing.id),{method:"PATCH",body:payload,accessToken:internal?undefined:token}))[0]:(await supabaseRequest("lead_opportunities",{method:"POST",body:payload,accessToken:internal?undefined:token}))[0];created.push(row);
  if(o.service==="website"&&(o.url||lead.website)){const old=(await supabaseRequest("website_audits?lead_id=eq."+encodeURIComponent(id)+"&order=created_at.desc&limit=1&select=*"))[0];const p={lead_id:id,url:o.url||lead.website,performance_score:o.performance_score??null,design_score:o.design_score??null,mobile_score:o.mobile_score??null,seo_score:o.seo_score??null,conversion_score:o.conversion_score??null,technology:o.technology||{},issues:o.issues||[],opportunities:o.opportunities||[],ai_summary:o.ai_summary||o.recommended_solution||null};if(old)await supabaseRequest("website_audits?id=eq."+old.id,{method:"PATCH",body:p});else await supabaseRequest("website_audits",{method:"POST",body:p});}
  if(o.service==="app"){const old=(await supabaseRequest("app_opportunities?lead_id=eq."+encodeURIComponent(id)+"&order=created_at.desc&limit=1&select=*"))[0];const p={lead_id:id,current_app:o.current_app||null,problem:o.problem||o.reason||null,recommended_app:o.recommended_app||o.recommended_solution||null,features:o.features||[],platform:o.platform||null,estimated_value:o.estimated_value==null?null:Number(o.estimated_value),ai_analysis:o.ai_analysis||o.reason||null};if(old)await supabaseRequest("app_opportunities?id=eq."+old.id,{method:"PATCH",body:p});else await supabaseRequest("app_opportunities",{method:"POST",body:p});}
  if(o.service==="automation"){const old=(await supabaseRequest("automation_opportunities?lead_id=eq."+encodeURIComponent(id)+"&order=created_at.desc&limit=1&select=*"))[0];const p={lead_id:id,current_process:o.current_process||null,pain_point:o.pain_point||o.reason||null,recommended_automation:o.recommended_automation||o.recommended_solution||null,tools:o.tools||[],workflow:o.workflow||{},estimated_time_saved:o.estimated_time_saved||null,estimated_value:o.estimated_value==null?null:Number(o.estimated_value),ai_analysis:o.ai_analysis||o.reason||null};if(old)await supabaseRequest("automation_opportunities?id=eq."+old.id,{method:"PATCH",body:p});else await supabaseRequest("automation_opportunities",{method:"POST",body:p});}
  if(o.service==="ai_video"){const old=(await supabaseRequest("video_opportunities?lead_id=eq."+encodeURIComponent(id)+"&order=created_at.desc&limit=1&select=*"))[0];const p={lead_id:id,brand:o.brand||lead.company_name,product:o.product||null,opportunity_type:o.opportunity_type||null,creative_angle:o.creative_angle||null,hook:o.hook||null,video_concept:o.video_concept||o.recommended_solution||null,platform:o.platform||null,estimated_value:o.estimated_value==null?null:Number(o.estimated_value),ai_analysis:o.ai_analysis||o.reason||null};if(old)await supabaseRequest("video_opportunities?id=eq."+old.id,{method:"PATCH",body:p});else await supabaseRequest("video_opportunities",{method:"POST",body:p});}
 }
 await supabaseRequest("leads?id=eq."+encodeURIComponent(id),{method:"PATCH",body:{status:"qualified",raw_data:{...(lead.raw_data||{}),last_analysis:result,last_analysis_at:new Date().toISOString()}},accessToken:internal?undefined:token});
 return res.json({lead_id:id,analysis:result,opportunities:created});
}catch(error){return res.status(error?.code==="FORBIDDEN"?403:error?.code==="NOT_FOUND"?404:error?.code==="AI_SCHEMA_INVALID"?422:400).json({error:error?.message||"Lead analysis failed",code:error?.code||"REQUEST_FAILED"});}}
