import {aiJSON} from "./ai.js";
import {validateMissionPlan,validateQA} from "./ai-schema.js";
import {supabaseRequest} from "./supabase.js";
const AGENT_RULES={
"orchestrator":"Turn the mission into a practical execution plan. Return JSON with tasks[]. Each task must have title, description, agent_slug, priority, dependencies, requires_approval and input.",
"research-agent":"Research the provided business or market context from supplied data only. Return structured findings, assumptions, risks and next_actions.",
"lead-hunter":"Analyze supplied lead/prospect information and return qualification, fit signals, missing information and recommended next action.",
"website-auditor":"Analyze supplied website information and return scores/issues/opportunities. Never claim live measurements unless supplied.",
"app-strategist":"Identify app/product opportunities. Return problem, recommended_app, features, platform, value rationale and risks.",
"automation-architect":"Design an automation. Return trigger, steps, systems, data flow, failure handling and approval points.",
"ai-video-strategist":"Design an AI-video opportunity. Return concept, audience, hook, scenes, production approach and CTA.",
"proposal-writer":"Draft a personalized proposal. Return subject, message, scope, deliverables, timeline and price assumptions. Never send it.",
"qa-inspector":"Validate another agent output against the supplied goal. Return pass, issues, corrections and confidence.",
"follow-up-manager":"Draft an approval-aware follow-up plan. Never send outreach. Return timing, channel, message and reason.",
"analytics-analyst":"Analyze supplied execution metrics and return findings, anomalies and optimization actions."
};
const json=v=>v??{};
async function insert(table,row){return (await supabaseRequest(table,{method:"POST",body:row}))[0];}
async function patch(table,query,row){return (await supabaseRequest(`${table}?${query}`,{method:"PATCH",body:row}))[0];}
async function getAgent(id){const rows=await supabaseRequest("agents?id=eq."+encodeURIComponent(id)+"&select=*");return rows[0];}
export async function createMission({userId,title,goal,services=[],priority="normal",targetCount=0}){if(!String(title||"").trim()||!String(goal||"").trim())throw new Error("title and goal are required");const mission=await insert("missions",{created_by:userId,title:String(title).trim(),goal:String(goal).trim(),services,priority,target_count:targetCount});await insert("agent_events",{mission_id:mission.id,event_type:"mission_created",message:"Mission created",metadata:{services}});return mission;}
export async function planMission(mission){
 const existing=await supabaseRequest("mission_tasks?mission_id=eq."+encodeURIComponent(mission.id)+"&select=*&order=created_at.asc");
 if(["planning_complete","running","waiting_approval","completed","failed","cancelled"].includes(mission.status)&&existing.length)return {mission,tasks:existing,idempotent:true};
 if(mission.status==="planning")throw new Error("Mission planning is already in progress");
 const agents=await supabaseRequest("agents?status=eq.active&select=id,name,slug,role,description,capabilities"),planner=agents.find(a=>a.slug==="orchestrator");if(!planner)throw new Error("Orchestrator agent is not seeded");
 await patch("missions","id=eq."+encodeURIComponent(mission.id)+"&status=eq."+encodeURIComponent(mission.status),{status:"planning",started_at:mission.started_at||new Date().toISOString()});
 const plan=validateMissionPlan(await aiJSON([{role:"system",content:"You are the Orchestrator for an AI Agency OS. Create an executable dependency-aware plan. Only use supplied mission context. Return valid JSON."},{role:"user",content:JSON.stringify({mission:{title:mission.title,goal:mission.goal,services:mission.services,priority:mission.priority,target_count:mission.target_count},available_agents:agents.map(a=>({slug:a.slug,name:a.name,role:a.role,capabilities:a.capabilities})),instructions:AGENT_RULES.orchestrator})}],{maxTokens:5000}));
 const slugSet=new Set(agents.map(a=>a.slug)),created=[];
 for(let i=0;i<plan.tasks.length;i++){const t=plan.tasks[i],slug=slugSet.has(t.agent_slug)?t.agent_slug:"research-agent",agent=agents.find(a=>a.slug===slug)||planner;const depIndexes=(Array.isArray(t.dependencies)?t.dependencies:[]).map(Number).filter(d=>Number.isInteger(d)&&d>=0&&d<i);const deps=depIndexes.map(d=>created[d]?.id).filter(Boolean);created.push(await insert("mission_tasks",{mission_id:mission.id,agent_id:agent.id,title:String(t.title),description:String(t.description),status:deps.length?"pending":"ready",priority:Number.isFinite(Number(t.priority))?Math.max(0,Math.min(100,Number(t.priority))):50,input:{...json(t.input),requires_approval:Boolean(t.requires_approval||t.input?.requires_approval),qa_required:t.input?.qa_required!==false},dependencies:deps,max_attempts:3}));}
 const planPayload={...plan,tasks:created.map(t=>({id:t.id,title:t.title,agent_id:t.agent_id,status:t.status,dependencies:t.dependencies}))};const updated=await patch("missions","id=eq."+encodeURIComponent(mission.id)+"&status=eq.planning",{status:"planning_complete",plan:planPayload});if(!updated)throw new Error("Mission state changed while planning");
 await insert("agent_events",{mission_id:mission.id,agent_id:planner.id,event_type:"mission_planned",message:`Created ${created.length} tasks`,metadata:{task_count:created.length}});return {mission:updated,tasks:created};
}
export function taskNeedsApproval(task){const input=task.input||{};if(input.requires_approval===true||input.external_action===true)return true;return ["send","publish","delete","deploy","contact","email","dm","outreach","purchase","irreversible"].some(k=>String(task.title+" "+task.description).toLowerCase().includes(k));}
async function refreshReadyTasks(missionId){const tasks=await supabaseRequest("mission_tasks?mission_id=eq."+encodeURIComponent(missionId)+"&select=*"),completed=new Set(tasks.filter(t=>t.status==="completed").map(t=>t.id));for(const t of tasks){if(t.status==="pending"&&Array.isArray(t.dependencies)&&t.dependencies.every(d=>completed.has(d)))await patch("mission_tasks","id=eq."+encodeURIComponent(t.id)+"&status=eq.pending",{status:"ready"});}return tasks;}
async function runQA(mission,task,agent,output){if(task.input?.qa_required===false||agent.slug==="qa-inspector")return {pass:true,issues:[],corrections:[],confidence:100};const qaAgent=(await supabaseRequest("agents?slug=eq.qa-inspector&status=eq.active&select=*"))[0];if(!qaAgent)return {pass:true,issues:["QA agent unavailable"],corrections:[],confidence:0};return validateQA(await aiJSON([{role:"system",content:AGENT_RULES["qa-inspector"]+" Be strict but only use supplied information."},{role:"user",content:JSON.stringify({mission:{title:mission.title,goal:mission.goal},task:{title:task.title,description:task.description},agent:agent.name,output})}],{maxTokens:2500}));}
export async function runNextTask(mission){
 await refreshReadyTasks(mission.id);
 const tasks=await supabaseRequest("mission_tasks?mission_id=eq."+encodeURIComponent(mission.id)+"&status=eq.ready&order=priority.asc,created_at.asc&limit=1&select=*");
 if(!tasks.length){const all=await supabaseRequest("mission_tasks?mission_id=eq."+encodeURIComponent(mission.id)+"&select=id,status"),remaining=all.filter(t=>["pending","ready","running"].includes(t.status)),failed=all.filter(t=>t.status==="failed"),approvals=await supabaseRequest("approvals?mission_id=eq."+encodeURIComponent(mission.id)+"&status=eq.pending&select=id");if(approvals.length)return {status:"waiting_approval",approvals};if(failed.length){await patch("missions","id=eq."+encodeURIComponent(mission.id),{status:"failed"});return {status:"failed",message:"Mission has failed tasks",failed_tasks:failed.map(t=>t.id)};}if(!remaining.length){const m=await patch("missions","id=eq."+encodeURIComponent(mission.id)+"&status=neq.completed",{status:"completed",completed_at:new Date().toISOString()});return {status:"completed",mission:m};}return {status:"blocked",message:"No task is currently ready"};}
 const task=tasks[0],agent=await getAgent(task.agent_id);if(!agent)throw new Error("Assigned agent not found");
 if(taskNeedsApproval(task)){const approvals=await supabaseRequest("approvals?task_id=eq."+encodeURIComponent(task.id)+"&select=id,status,action,reason,created_at,resolved_at,approved_by&order=created_at.desc");const authoritative=approvals.find(a=>a.status==="approved"||a.status==="rejected");if(authoritative?.status==="rejected"){await patch("mission_tasks","id=eq."+encodeURIComponent(task.id),{status:"cancelled",completed_at:new Date().toISOString(),locked_at:null,heartbeat_at:null});await patch("missions","id=eq."+encodeURIComponent(mission.id),{status:"failed"});await insert("agent_events",{mission_id:mission.id,task_id:task.id,agent_id:agent.id,event_type:"approval_rejected",message:"Human approval rejected; task will not execute",metadata:{approval_id:authoritative.id}});return {status:"failed",task_id:task.id,approval_id:authoritative.id,reason:"Approval rejected"};}if(authoritative?.status!=="approved"){const pending=approvals.find(a=>a.status==="pending");if(!pending){let created;try{created=await insert("approvals",{mission_id:mission.id,task_id:task.id,action:"external_action",payload:{task_id:task.id,title:task.title,description:task.description,input:task.input},reason:"External or irreversible action requires human approval",status:"pending"});}catch(error){const concurrent=await supabaseRequest("approvals?task_id=eq."+encodeURIComponent(task.id)+"&status=eq.pending&select=id&limit=1");if(!concurrent.length)throw error;created=concurrent[0];}await patch("missions","id=eq."+encodeURIComponent(mission.id),{status:"waiting_approval"});await insert("agent_events",{mission_id:mission.id,task_id:task.id,agent_id:agent.id,event_type:"approval_required",message:"Human approval required before execution",metadata:{approval_id:created.id}});return {status:"waiting_approval",task,approval_id:created.id};}await patch("missions","id=eq."+encodeURIComponent(mission.id),{status:"waiting_approval"});return {status:"waiting_approval",task,approval_id:pending.id};}}
 const attempt=(task.attempt_count||0)+1,maxAttempts=task.max_attempts||3;const claimed=await supabaseRequest("mission_tasks?id=eq."+encodeURIComponent(task.id)+"&status=eq.ready",{method:"PATCH",body:{status:"running",attempt_count:attempt,locked_at:new Date().toISOString(),heartbeat_at:new Date().toISOString(),started_at:task.started_at||new Date().toISOString()}});if(!claimed.length)return {status:"busy",message:"Task was claimed by another worker",task_id:task.id};
 const run=await insert("agent_runs",{mission_id:mission.id,task_id:task.id,agent_id:agent.id,status:"running",attempt,input:task.input});
 try{const output=await aiJSON([{role:"system",content:`You are the ${agent.name} in an AI Agency OS. ${AGENT_RULES[agent.slug]||agent.description||"Complete the task safely and return structured JSON."} Never perform external actions yourself.`},{role:"user",content:JSON.stringify({mission:{id:mission.id,title:mission.title,goal:mission.goal,services:mission.services},task:{id:task.id,title:task.title,description:task.description,input:task.input,attempt},agent:{name:agent.name,role:agent.role,capabilities:agent.capabilities}})}],{maxTokens:5000});const qa=await runQA(mission,task,agent,output);
 if(qa.pass!==true){const retry=attempt<maxAttempts;await patch("mission_tasks","id=eq."+encodeURIComponent(task.id),{status:retry?"ready":"failed",output:{result:output,qa},qa_status:"failed",qa_output:qa,locked_at:null,heartbeat_at:null,completed_at:retry?null:new Date().toISOString()});await patch("agent_runs","id=eq."+encodeURIComponent(run.id),{status:"failed",output:{result:output,qa},error:"QA rejected task",completed_at:new Date().toISOString()});await insert("agent_events",{mission_id:mission.id,task_id:task.id,agent_id:agent.id,event_type:retry?"qa_retry":"qa_failed",message:retry?"QA rejected output; retrying":"QA rejected output; retry limit reached",metadata:{attempt,maxAttempts,qa}});if(!retry)await patch("missions","id=eq."+encodeURIComponent(mission.id),{status:"failed"});return {status:retry?"retrying":"failed",task_id:task.id,qa};}
 await patch("mission_tasks","id=eq."+encodeURIComponent(task.id),{status:"completed",output,qa_status:"passed",qa_output:qa,locked_at:null,heartbeat_at:null,completed_at:new Date().toISOString()});await patch("agent_runs","id=eq."+encodeURIComponent(run.id),{status:"completed",output,completed_at:new Date().toISOString()});await insert("agent_events",{mission_id:mission.id,task_id:task.id,agent_id:agent.id,event_type:"task_completed",message:`${agent.name} completed and passed QA`,metadata:{attempt,qa}});await refreshReadyTasks(mission.id);const refreshed=await supabaseRequest("mission_tasks?mission_id=eq."+encodeURIComponent(mission.id)+"&select=id,status"),hasFailed=refreshed.some(t=>t.status==="failed"),hasWork=refreshed.some(t=>["pending","ready","running"].includes(t.status));await patch("missions","id=eq."+encodeURIComponent(mission.id),{status:hasFailed?"failed":hasWork?"running":"completed",completed_at:hasFailed||hasWork?null:new Date().toISOString()});return {status:"completed",task_id:task.id,agent:agent.name,output,qa};
 }catch(error){const retry=attempt<maxAttempts;await patch("mission_tasks","id=eq."+encodeURIComponent(task.id),{status:retry?"ready":"failed",output:{error:error.message},locked_at:null,heartbeat_at:null,completed_at:retry?null:new Date().toISOString()});await patch("agent_runs","id=eq."+encodeURIComponent(run.id),{status:"failed",error:error.message,completed_at:new Date().toISOString()});await insert("agent_events",{mission_id:mission.id,task_id:task.id,agent_id:agent.id,event_type:retry?"task_retry":"task_failed",message:error.message,metadata:{attempt,maxAttempts}});if(!retry)await patch("missions","id=eq."+encodeURIComponent(mission.id),{status:"failed"});return {status:retry?"retrying":"failed",task_id:task.id,error:error.message};}
}
export async function recoverStaleTasks({maxAgeMinutes=15}={}){const cutoff=new Date(Date.now()-maxAgeMinutes*60000).toISOString(),stale=await supabaseRequest("mission_tasks?status=eq.running&locked_at=lt."+encodeURIComponent(cutoff)+"&select=id,mission_id,attempt_count,max_attempts");for(const task of stale){const retry=(task.attempt_count||0)<(task.max_attempts||3);await patch("mission_tasks","id=eq."+encodeURIComponent(task.id)+"&status=eq.running",{status:retry?"ready":"failed",locked_at:null,heartbeat_at:null});if(!retry)await patch("missions","id=eq."+encodeURIComponent(task.mission_id),{status:"failed"});await insert("agent_events",{mission_id:task.mission_id,task_id:task.id,event_type:"stale_task_recovered",message:retry?"Stale task reset for retry":"Stale task exhausted retries",metadata:{attempt_count:task.attempt_count,max_attempts:task.max_attempts}});}return {recovered:stale.length};}
export async function getMission(id,accessToken){const missions=await supabaseRequest("missions?id=eq."+encodeURIComponent(id)+"&select=*",{accessToken});if(!missions.length)throw new Error("Mission not found");const tasks=await supabaseRequest("mission_tasks?mission_id=eq."+encodeURIComponent(id)+"&select=*&order=created_at.asc",{accessToken});const approvals=await supabaseRequest("approvals?mission_id=eq."+encodeURIComponent(id)+"&select=*&order=created_at.desc",{accessToken});return {mission:missions[0],tasks,approvals};}
